### ISSUE TITLE
Kernel 6.9.0 does not compile with v6.7 patches.

### ISSUE THREAD

**Issue by pimzand** [AmpereComputing/linux-ampere-altra-erratum-pcie-65#1]
When applying the 6.7 patches to a vanilla 6.9.0 kernel, the kernel no longer compiles.
Compiling on Fedora 40:

```
$ make vmlinuz.efi
  CC      arch/arm64/kernel/asm-offsets.s
In file included from ./arch/arm64/include/asm/kasan.h:10,
                 from ./arch/arm64/include/asm/processor.h:40,
                 from ./include/asm-generic/qrwlock.h:18,
                 from ./arch/arm64/include/generated/asm/qrwlock.h:1,
                 from ./arch/arm64/include/asm/spinlock.h:9,
                 from ./include/linux/spinlock.h:95,
                 from ./include/linux/mmzone.h:8,
                 from ./include/linux/gfp.h:7,
                 from ./include/linux/slab.h:16,
                 from ./include/linux/resource_ext.h:11,
                 from ./include/linux/acpi.h:13,
                 from ./include/acpi/apei.h:9,
                 from ./include/acpi/ghes.h:5,
                 from ./include/linux/arm_sdei.h:8,
                 from arch/arm64/kernel/asm-offsets.c:10:
./arch/arm64/include/asm/pgtable.h: In function ‘pte_mkspecial’:
./arch/arm64/include/asm/pgtable.h:615:50: error: ‘PTE_ADDR_MASK’ undeclared (first use in this function); did you mean ‘PTE_TYPE_MASK’?
  615 |         pgprot_t prot = __pgprot(pte_val(pte) & ~PTE_ADDR_MASK);
      |                                                  ^~~~~~~~~~~~~
./arch/arm64/include/asm/pgtable-types.h:51:40: note: in definition of macro ‘__pgprot’
   51 | #define __pgprot(x)     ((pgprot_t) { (x) } )
      |                                        ^
./arch/arm64/include/asm/pgtable.h:615:50: note: each undeclared identifier is reported only once for each function it appears in
  615 |         pgprot_t prot = __pgprot(pte_val(pte) & ~PTE_ADDR_MASK);
      |                                                  ^~~~~~~~~~~~~
./arch/arm64/include/asm/pgtable-types.h:51:40: note: in definition of macro ‘__pgprot’
   51 | #define __pgprot(x)     ((pgprot_t) { (x) } )
      |                                        ^
make[2]: *** [scripts/Makefile.build:117: arch/arm64/kernel/asm-offsets.s] Error 1
make[1]: *** [/home/pim/os/linux/kernel/linux/Makefile:1197: prepare0] Error 2
make: *** [Makefile:240: __sub-make] Error 2
```

**Comment by Civil** [comment]
1. You need to change `PTE_ADDR_MASK` to `PHYS_TO_PTE_ADDR_MASK`, that was changed by that commit: https://lore.kernel.org/all/20221124123932.2648991-12-ardb@kernel.org/
2. Because it is now ifdef'ed on `CONFIG_ARM64_PA_BITS_52` - you need to enable that option (I've added select in KConfig).

But it would be actually great to have official validation that this is exactly what needs to be done, as frankly speaking I'm not sure that new definition of `PHYS_TO_PTE_ADDR_MASK` for non-64K pages is still do the job as I only vaguely understand what patch was trying to do.

**Comment by d-scott-phillips** [comment]
@pimzand can you check that the change in #3 works for you?

**Comment by pimzand** [comment]
Hi @d-scott-phillips  yes it works for me; kernel is still building, though, but I am now beyond the point of failure.

But rather than patching the v6.7 patch tree, wouldn't it be better to create new patch trees for different kernel versions?

**Comment by Civil** [comment]
@pimzand it could be better to ifdef depending on the PA_BITS_52 and use a define there when available, or fallback to alternative if not. Unless there is a specific reason I'm not aware of why the new approach is better.

**Comment by pimzand** [comment]
> And I think the main question here should be: why not to work on making the workaround upstream? Surely it must target only Ampere Altra CPUs (so it won't potentially affect other systems), but that way everyone will have it built-in and available.

Agreed, but upsteream will never accept patches that do not apply and compile on latest git so these should there be first.
Another thing that may be needed is activation using the kernel command line, so it can be used in bianry kernels.

**Comment by d-scott-phillips** [comment]
> But rather than patching the v6.7 patch tree, wouldn't it be better to create new patch trees for different kernel versions?

The policy here is that as long as the patch remains working on v6.7, the patch will stay in that directory. We will split the patches if it becomes impossible to support multiple kernel versions with one set of patches.

> since you are not using a preprocessor defined value here, I suppose that there is no necessity to select CONFIG_ARM64_PA_BITS_52

That's right, both settings of that CONFIG should be supported.
