### ISSUE TITLE
v6.12 patches do not compile on kernel 6.13

### ISSUE THREAD

**Issue by pimzand** [AmpereComputing/linux-ampere-altra-erratum-pcie-65#7]
```
$ make kernelversion
6.13.0
$ make -j1 vmlinuz.efi
  CALL    scripts/checksyscalls.sh
  DESCEND bpf/resolve_btfids
  INSTALL libsubcmd_headers
  CC      arch/arm64/kernel/alignment.o
arch/arm64/kernel/alignment.c:14:10: fatal error: asm/patching.h: No such file or directory
   14 | #include <asm/patching.h>
      |          ^~~~~~~~~~~~~~~~
compilation terminated.
make[4]: *** [scripts/Makefile.build:194: arch/arm64/kernel/alignment.o] Error 1
make[3]: *** [scripts/Makefile.build:440: arch/arm64/kernel] Error 2
make[2]: *** [scripts/Makefile.build:440: arch/arm64] Error 2
make[1]: *** [Makefile:1989: .] Error 2
make: *** [Makefile:251: __sub-make] Error 2

```
